services:
  db:
    container_name: saas-shadcn-db
    image: yassinsiouda/saas-shadcn-db:latest
    build: db/
    ports:
      - "${dbEND_PORT}:8090"
    volumes:
      - ./db/pb_migrations/:/pb_migrations
      - ./db/pb_data/:/pb_data/
  front:
    image: yassinsiouda/saas-shadcn-front:latest
    container_name: saas-shadcn-front
    build: 
      context: front/
      target: "prod"
    volumes:
      - ./front/src/:/app/src
    ports:
      - "${FRONT_PORT}:5173" #keep same port to avoid Cross scripting errors
    env_file:
      - .env
  landing:
    image: yassinsiouda/saas-shadcn-landing:latest
    container_name: saas-shadcn-landing
    build: 
      context: landing/
      target: "prod"
    volumes:
      - ./landing/src/:/app/src
    ports:
      - "${LANDING_PORT}:5173" #keep same port to avoid Cross scripting errors
    env_file:
      - .env