name: Build and Push Docker Images

on:
  push:
    branches:
      - 'main'
      - 'dev'
    # add tags to trigger the workflow

jobs:
  back:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./back
          # if brach is main use prod target else use dev
          target: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
          # based on branch push tag latest for main and dev for dev
          tags: yassinsiouda/saas-shadcn-back:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
  db:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./db
          # based on branch push tag latest for main and dev for dev
          tags: yassinsiouda/saas-shadcn-db:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
  front:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./front
          # if brach is main use prod target else use dev
          target: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
          # based on branch push tag latest for main and dev for dev
          tags: yassinsiouda/saas-shadcn-front:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
  landing:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./landing
          # if brach is main use prod target else use dev
          target: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
          # based on branch push tag latest for main and dev for dev
          tags: yassinsiouda/saas-shadcn-landing:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}